### ISSUE TITLE
Mac OS no work 

### ISSUE THREAD

**Issue by dedm1** [yellow-footed-honeyguide/facad#4]
на маке ошибка когда используешь команду ninja
../src/args_parser.c:22:19: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]

что бы пофиксить надо 
в файле ./src/args_parser.c заменить 22 строчку с 
void print_version() {
на 
void print_version(void) {
и заново ввести команду ninja 

поправьте пожалуйста

**Comment by yellow-footed-honeyguide** [comment]
@dedm1 , thank you for noticing this issue, it has been fixed in the new release.
