### ISSUE TITLE
Give an exact error message when the file is not found

### ISSUE THREAD

**Issue by dmikushin** [yellow-footed-honeyguide/facad#9]
When the folder does not exist, facad's error reporting is mesleading:

```bash
►ls test
Error: Unexpected argument 'test'
Usage: ls [OPTION] [DIRECTORY]
Try 'ls --help' for more information.
```

It would be very useful to have a more exact error message about invalid file or directory:

```bash
►ls.coreutils test
ls.coreutils: cannot access 'test': No such file or directory
```

**Comment by yellow-footed-honeyguide** [comment]
Thank you, @dmikushin  !
I fixed it.

![scr_20241009_183750](https://github.com/user-attachments/assets/aac80fd1-48dc-416b-9720-23486730810c)
